### ISSUE TITLE
[v2.7] Stage Manager recent apps area not respected anymore

### ISSUE THREAD

**Issue by Tekl** [rxhanson/RectanglePro-Community#157] opened 2022-11-02 09:29 UTC
After updating to v2.7, maximizing windows will overlap the recent apps area so that it disappears. In the previous version it worked well. The setting "Stage Manager recent apps area" seems to have no effect on my system.

I'm using v2.7 (126) on macOS 13.0 (22A380) with German locale.

**Comment by rxhanson** [comment] 2022-11-02 11:53
Thanks for reporting. I can't reproduce this. Are you using more than one display?

Can you provide logs?
Hold option in the menu bar menu and select "View Logging..."

This could be a situation where the macOS settings for stage manager being enabled are not being communicated properly to Rectangle Pro. Perhaps logging out and logging back in will get it back on track?

**Comment by Tekl** [comment] 2022-11-02 14:33
I found the reason. After problems with Stage Manger, I deleted it preferences. Thus, the Key `AutoHide` was missing in `com.apple.WindowManager`. After disabling and enabling the recents apps option everything works fine.

**Comment by rxhanson** [comment] 2022-11-02 14:50
Great, thanks for the investigation and follow up. I'll close this one out and keep it in mind for future troubleshooting.

**Closed by rxhanson** 2022-11-02 14:50 UTC
